version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/webd
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - arm
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: true
  mode: replace
