version: 2

before:
  hooks:
    - go mod init webd
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "webd_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: false
  mode: replace
